/** @file cmdline.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22.6
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "Algoritmo genetico binario para optmizacion de funciones"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "Algoritmo genetico binario para optmizacion de funciones"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "1.0"
#endif

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * instancia_arg;	/**< @brief Archivo que contiene la instancia a resolver..  */
  char * instancia_orig;	/**< @brief Archivo que contiene la instancia a resolver. original value given at command line.  */
  const char *instancia_help; /**< @brief Archivo que contiene la instancia a resolver. help description.  */
  int numgen_arg;	/**< @brief Numero maximo de generaciones a ejecutar. (default='500').  */
  char * numgen_orig;	/**< @brief Numero maximo de generaciones a ejecutar. original value given at command line.  */
  const char *numgen_help; /**< @brief Numero maximo de generaciones a ejecutar. help description.  */
  double mut_arg;	/**< @brief Probabilidad de mutacion del algoritmo. (default='0.1').  */
  char * mut_orig;	/**< @brief Probabilidad de mutacion del algoritmo. original value given at command line.  */
  const char *mut_help; /**< @brief Probabilidad de mutacion del algoritmo. help description.  */
  double cross_arg;	/**< @brief Probabilidad de cruzamiento del algoritmo. (default='0.9').  */
  char * cross_orig;	/**< @brief Probabilidad de cruzamiento del algoritmo. original value given at command line.  */
  const char *cross_help; /**< @brief Probabilidad de cruzamiento del algoritmo. help description.  */
  int pop_arg;	/**< @brief Tamano de la poblacion del algoritmo. (default='50').  */
  char * pop_orig;	/**< @brief Tamano de la poblacion del algoritmo. original value given at command line.  */
  const char *pop_help; /**< @brief Tamano de la poblacion del algoritmo. help description.  */
  int srand_arg;	/**< @brief Semilla a utilizar para la generacion de numeros aleatoreos (debe ser un numero entero). (default='100').  */
  char * srand_orig;	/**< @brief Semilla a utilizar para la generacion de numeros aleatoreos (debe ser un numero entero). original value given at command line.  */
  const char *srand_help; /**< @brief Semilla a utilizar para la generacion de numeros aleatoreos (debe ser un numero entero). help description.  */
  int debug_flag;	/**< @brief Si debug esta off solo se muestra el resultado junto con el valor de las variables. En on se despliega informacion interesante sobre el estado del algoritmo. (default=off).  */
  const char *debug_help; /**< @brief Si debug esta off solo se muestra el resultado junto con el valor de las variables. En on se despliega informacion interesante sobre el estado del algoritmo. help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int instancia_given ;	/**< @brief Whether instancia was given.  */
  unsigned int numgen_given ;	/**< @brief Whether numgen was given.  */
  unsigned int mut_given ;	/**< @brief Whether mut was given.  */
  unsigned int cross_given ;	/**< @brief Whether cross was given.  */
  unsigned int pop_given ;	/**< @brief Whether pop was given.  */
  unsigned int srand_given ;	/**< @brief Whether srand was given.  */
  unsigned int debug_given ;	/**< @brief Whether debug was given.  */

} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
